name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

  build-lib:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build lib
        run: mvn -B verify --file pom.xml -P lib

  build-app:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build app
        run: mvn -B verify --file pom.xml -P app
